#!/bin/bash

ROOT_DIR=$(pwd)
DEPS_DIR=$ROOT_DIR/deps
BIN_DIR=$DEPS_DIR/bin
INCLUDE_DIR=$DEPS_DIR/include
LIB_DIR=$DEPS_DIR/lib
LIB64_DIR=$DEPS_DIR/lib64

export LDFLAGS="$LDFLAGS -L$LIB_DIR"
export LDFLAGS="$LDFLAGS -L$LIB64_DIR"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIB_DIR"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LIB64_DIR"
export LIBRARY_DIRS="$LIBRARY_DIRS:$LD_LIBRARY_PATH"
export CPATH="$CPATH:$INCLUDE_DIR"
export PATH=$PATH:$BIN_DIR

# HDF5-specific flag for UNN cluster file system.
export HDF5_USE_FILE_LOCKING=FALSE